### ISSUE TITLE
Image to pattern doesn't seem to be working

### ISSUE THREAD

**Issue by jcwenzel** [x-raizor/Efficiency#1]
Version of Sketch: Version 3.3 (11970)
OS: 10.10.02

Here is a video of what is happening: https://drive.google.com/file/d/0Bw5I1jx2PlbTZVBRNXBPVjNSeGs/view?usp=sharing

**Comment by x-raizor** [comment]
@jcwenzel, please check now the latest version. Thank you for reporting!

**Comment by jcwenzel** [comment]
It works perfectly now!!!! Thank you sir.
