### ISSUE TITLE
List to seperate textboxes

### ISSUE THREAD

**Issue by Jursdotme** [x-raizor/Efficiency#2]
I have an idea but not the cocoa skills to make it happen and thought i would reach out to you.

I had an idear for a script that takes a single textbox and separates each line into individual textboxes.
I see this as a fast way to create navigation and menus.

I dont see this as a very complex piece of coding but i think it would be usefull.

Any thoughts?

**Comment by x-raizor** [comment]
@Jursdotme, it is already done here:

https://github.com/joshwayne/jw-sketch-plugins/blob/master/Text/Split%20Text%20Lines%20to%20Layers.sketchplugin

Андрей Шапиро

**Comment by Jursdotme** [comment]
Thats awesome. Been looking for something like this. Thank you :-)
