### ISSUE TITLE
Rounded rectangle layer

### ISSUE THREAD

**Issue by jarisanders** [x-raizor/Efficiency#3]
Thanks for creating this plugin, saves me a lot of time!
Would love to be able to add rounded corners to my converted bitmaps, I tried playing around with the code myself but no luck.

**Comment by x-raizor** [comment]
@jarisanders you can use 'Bitmap to Pattern Fill' command of the plugin to convert image into rectangle. After that you will be able easely adjust roundness of its corners. The only drawback on your way maybe selecting anchor points. I do it by pressing Enter and then Cmd + A. Then you can adjust roundness on cornes fader. Look at the screencast:

![Screencast](http://d.pr/i/189hQ+)

**Comment by jarisanders** [comment]
That's what I'm currently doing too, being able to adjust it like a regular rounded rectangle would be a bit easier though.

**Comment by x-raizor** [comment]
So, I couldn't catch what do you need else in it? What idea do you have? :-) 

Андрей Шапиро
