### ISSUE TITLE
Bitmap To Pattern Fill перестал работать в Sketch 3.4

### ISSUE THREAD

**Issue by IvanMayorov** [x-raizor/Efficiency#4]
Привет, очень люблю ваш плагин, но после обновления перестал работать Bitmap To Pattern Fill. Можно его как-то починить? Спасибо.

**Comment by abynim** [comment]
@x-raizor please update this line: https://github.com/x-raizor/Efficiency/blob/master/Bitmap%20To%20Pattern%20Fill.sketchplugin#L26

to:

```
rawImage = (sketchVersion >= 3.4) ? [layer NSImage] : [[layer image] image]
```

I believe that's the only update required, but let me know if that doesn't fix the issue.

**Comment by x-raizor** [comment]
@abynim 
Thanks Aby! 
Very nice shot!
That works fine.

**Comment by x-raizor** [comment]
@IvanMayorov поправили, скачайте последнюю версию. Спасибо за репорт!

**Comment by IvanMayorov** [comment]
Всё работает, супер, спасибо за оперативность!
