### ISSUE TITLE
Bitmap to pattern fill doesn't work

### ISSUE THREAD

**Issue by Bagawarman** [x-raizor/Efficiency#5]
Nice plugin, but "bitmap to pattern fill" doesn't work on sketch 3.5

**Comment by x-raizor** [comment]
@abynim any ideas what was changed in 3.5 about this? I haven't found yet.

**Comment by abynim** [comment]
@x-raizor just sent a PR. Let me know if that fixes it :)

**Comment by x-raizor** [comment]
many thanks, @abynim!

**Comment by x-raizor** [comment]
@Bagawarman please update the plugin — we have made an update recently
