### ISSUE TITLE
Text LineSpacing +/- keyboard shortcut not working

### ISSUE THREAD

**Issue by mikeprecious** [x-raizor/Efficiency#7]
Can't seem to trigger this command with or without the kb shortcut. Would be great to see this tweaked to work again in the latest release of Sketch. 

Thanks

**Comment by x-raizor** [comment]
Mike! Thank your for feedback. I’m suffering without this functionality too. Will try to fix it in nearest future.

**Comment by mikeprecious** [comment]
Thanks! I speak on behalf of myself and the Sketch user community - thanks for your work on this plugin. Very useful. Keep us posted on the troubleshooting.

**Comment by x-raizor** [comment]
@mikeprecious I've made correction about text manipulations. Now LineHeight and ParagraphGap work. Please, take a look. Does it work for you?

**Comment by mikeprecious** [comment]
Thanks - working now!

**Comment by x-raizor** [comment]
@mikeprecious I've just corrected plugins for lineHeight. They now work with auto values. In the previous version if lineHeight was auto plugin started with zero lineHeight.

So, please update your version of plugin from repository.
