### ISSUE TITLE
Bitmap to Pattern Fill not working in 3.8

### ISSUE THREAD

**Issue by lyapustin** [x-raizor/Efficiency#8]
It just creating an layer on top of layers list with no fill. 
![android_production 2016-06-20 10-39-30](https://cloud.githubusercontent.com/assets/8135957/16186491/7a63eac2-36d3-11e6-9cb9-983d2c07ebc1.png)

**Comment by x-raizor** [comment]
@lyapustin I've resolved the problem. Please, download the last version. Does it work for you?

**Comment by lyapustin** [comment]
@x-raizor Yes, now it's works. Great, thank you!

**Comment by rohapa** [comment]
Doesn't work anymore
