### ISSUE TITLE
Bitmap to Pattern Fill no longer works in 39.1 (31720)

### ISSUE THREAD

**Issue by rohapa** [x-raizor/Efficiency#9]
Nothing happens when using the plugin.
Presents the message:

ReferenceError: Can't find variable: selection
line: 16

**Comment by x-raizor** [comment]
Hello @rohapa! Thank you for the report. I will take a look in a while.

**Comment by lyapustin** [comment]
Any ideas when this option will be back to work?

**Comment by abynim** [comment]
@x-raizor When you get a chance please review and accept PR #11 which _should_ fix this.

**Comment by lyapustin** [comment]
@abynim, thanks, it works!
_(upd: everything is ok)_

**Comment by lyapustin** [comment]
@abynim, nope, there is a bug. I'm applied script to image-1, then when apply it to image-2 — I'm getting fill with image-1.

**Comment by x-raizor** [comment]
@rohapa @lyapustin @abynim I've merged Aby's version and added toolbar update to see that fill is updated.  I also rearranged 'Efficiency' plugins in one package file to avoid deprecation of legacy format in near future. Please, check it out.
